name: Unit Tests

on: [pull_request]

jobs:
    frontend-tests:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}
            - name: npm install
              run: cd frontend && npm ci
            - name: tests
              run: cd frontend && npm test

    backend-tests:
        runs-on: ubuntu-latest
        
        strategy:
            matrix:
                node-version: [20.x]
        
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}
            - name: npm install
              run: cd backend && npm ci
            - name: tests
              run: cd backend && npm test